version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - "./:/var/www"
    networks:
      - "my-nw"
    container_name: app

  nginx:
    image: nginx:1.27.4
    ports:
      - "80:80"
    volumes:
      - "./:/var/www"
      - "./_docker/nginx/conf.template:/etc/nginx/conf.d/default.conf:ro"
    depends_on:
      - app
    networks:
      - "my-nw"
    container_name: nginx

  database:
    image: mysql:8.4.4
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - "my-nw"
    container_name: database

networks:
  my-nw:

volumes:
  mysql_data:
